export const products = [
 {
 id: "lei-1",
 storeSlug: "lei",
 externalId: "wool-scarf",
 name: "Wool Scarf",
 price: "$120",
 category: "Accessories",
 },
 {
 id: "lei-2",
 storeSlug: "lei",
 externalId: "vintage-cashmere-coat",
 name: "Vintage Cashmere Coat",
 price: "$380",
 category: "Clothes",
 },
 {
 id: "scottie-1",
 storeSlug: "sourced-by-scottie",
 externalId: "italian-leather-jacket",
 name: "Italian Leather Jacket",
 price: "$540",
 category: "Clothes",
 },
 {
 id: "scottie-2",
 storeSlug: "sourced-by-scottie",
 externalId: "handmade-leather-boots",
 name: "Handmade Leather Boots",
 price: "$420",
 category: "Shoes",
 },
 {
 id: "repark-1",
 storeSlug: "re-park-city",
 externalId: "vintage-ski-jacket",
 name: "Vintage Ski Jacket",
 price: "$260",
 category: "Clothes",
 },
 {
 id: "repark-2",
 storeSlug: "re-park-city",
 externalId: "western-leather-belt",
 name: "Western Leather Belt",
 price: "$95",
 category: "Accessories",
 },
];
