-- Normalize legacy non-canonical store_slug values to their canonical form
-- (e.g. "sassysowhat" -> "sassy-so-what", "bloda-s-choice" -> "blodas-choice").
-- ONLY rows whose alphanumeric-only form matches a known canonical slug are changed,
-- so genuinely unknown slugs (e.g. "the-vntg-collective", "velvet-archive") are left
-- untouched on purpose. Idempotent and safe to re-run.
--
-- NOTE: the 'products' table is intentionally NOT included — its store_slug is part of
-- the composite product id (store_slug-id) that other tables reference. The only
-- non-canonical product slug found ("the-vntg-collective") is UNKNOWN and needs a
-- manual decision (add the store to config, or remap it to its real slug) before any
-- product rows are touched.

-- ============ PREVIEW (read-only — run these first) ============

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'conversions' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM conversions x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'clicks' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM clicks x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'user_cart_items' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM user_cart_items x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'store_favorites' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM store_favorites x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'insider_seen_products' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM insider_seen_products x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'sold_items' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM sold_items x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  SELECT 'sourcing_offers' AS tbl, x.store_slug AS current_slug, canon.slug AS canonical_slug, COUNT(*)::int AS rows
  FROM sourcing_offers x
  JOIN canon ON regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
  WHERE x.store_slug <> canon.slug
  GROUP BY x.store_slug, canon.slug
  ORDER BY current_slug;

-- ============ APPLY (run after reviewing the previews) ============

BEGIN;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE conversions x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE clicks x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE user_cart_items x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE store_favorites x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE insider_seen_products x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE sold_items x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

  WITH canon(slug) AS (VALUES
    ('ange-archive'),
    ('ascensio-vintage'),
    ('bag-crush'),
    ('blodas-choice'),
    ('capsule-edit'),
    ('carroll-street-vintage'),
    ('chill-boutique'),
    ('chomp-chomp-vintage'),
    ('club-fleur'),
    ('dayton-jane'),
    ('dear-muse'),
    ('edited-archive'),
    ('for-the-globe'),
    ('front-page-finds'),
    ('hachi-archive'),
    ('honey-bear-vintage'),
    ('house-on-a-chain'),
    ('jade-vintage'),
    ('keepin-it-real-luxe'),
    ('lei-vintage'),
    ('lover-girl-vintage'),
    ('maison-optimism-vintage'),
    ('missi-archives'),
    ('montrose-edit'),
    ('mookie-studios'),
    ('moonstruck-vintage'),
    ('nello-vintage'),
    ('other-matters-atelier'),
    ('petria-vintage'),
    ('porters-preloved'),
    ('promised-vintage'),
    ('rareality-archive'),
    ('rejects-only-vintage'),
    ('sablier-vintage'),
    ('sarah-does'),
    ('sassy-so-what'),
    ('scarz-vintage'),
    ('sheer-vintage'),
    ('situations-vintage'),
    ('so-lxury'),
    ('source-twenty-four'),
    ('sourced-by-scottie'),
    ('tess-elizabeth-vintage'),
    ('the-objects-of-affection'),
    ('to-us-vintage'),
    ('vangie'),
    ('vintage-archives-la'),
    ('vintage-girlfriend'),
    ('vintari-vault'),
    ('west-village-vintage')
  )
  UPDATE sourcing_offers x SET store_slug = canon.slug
  FROM canon
  WHERE regexp_replace(lower(x.store_slug), '[^a-z0-9]', '', 'g') = regexp_replace(canon.slug, '[^a-z0-9]', '', 'g')
    AND x.store_slug <> canon.slug;

COMMIT;
